genome_name:
  "hg38"
data_files_folder:
  "/home/daric/work_WGGC/SV_annotation/sv_nanotation_snake/data"
own_database_file:
  "/home/daric/work_WGGC/SV_annotation/sv_nanotation_snake/data/full_database.bed"
base_dir:
  "/home/daric/work_WGGC/SV_annotation/sv_nanotation_snake"
header_file:
  #"/home/daric/work_WGGC/SV_annotation/sv_nanotation_snake/data/needed_header.smap" #- if the parents information is in the original  .smap
  "/home/daric/work_WGGC/SV_annotation/sv_nanotation_snake/data/needed_header_no_fam.smap"
max_freq:
  1
log_dir:
  "/home/daric/work_WGGC/SV_annotation/sv_nanotation_snake/logs"
