snakemake logs/database_add_41748_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_41864_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_41910_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_41926_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_43671_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_43677_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_43781_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_43811_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_43868_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_44659_ds-to-480G_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_44659_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_44908_child_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_44975_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45119_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45119_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45191_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45191_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45193_ds-to-480G_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45193_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45202_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45202_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45285_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45285_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45380-ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45380_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45508_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45508_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45568_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45568_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45595_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45595_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45616_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45616_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45746_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45746_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45851_ds-to-480G_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_45851_rvp_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_46358_rvp_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_46386_rvp_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_GLH-Fibro01_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_Kontrolle_AG_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_Kontrolle_HJL_assembly_151_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_Kontrolle_HS_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_needed_header_no_fam.log --cores 2 --latency-wait 60
snakemake logs/database_add_needed_header.log --cores 2 --latency-wait 60
snakemake logs/database_add_new_test_infile_12aug.log --cores 2 --latency-wait 60
snakemake logs/database_add_raw_keimbahn.log --cores 2 --latency-wait 60_infile.smap
snakemake logs/database_add_rvp_test_infile_converted.log --cores 2 --latency-wait 60
snakemake logs/database_add_rvp_test_infile.log --cores 2 --latency-wait 60
snakemake logs/database_add_Sample01_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_Sample02_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
snakemake logs/database_add_Sample03_assembly_152_variants_combine_filters_inMoleRefine1.log --cores 2 --latency-wait 60
